[package]
name = "ash"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.18", features = ["derive"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
directories = "4.0.1"
fuzzy-matcher = "0.3.7"
handlebars = "4.3.5"
inquire = "0.4.0"
itertools = "0.10.5"
pollster = "0.2.5"
ssh_cfg = "0.3.0"
http = "0.2.8"
minreq = { version = "2.6.0", features = ["https"] }
aws-sigv4 = "0.51.0"
rust-ini = "0.18.0"
roxmltree = "0.15.1"
chrono = "0.4.22"

[profile.release]
strip = true    # Automatically strip symbols from the binary.
opt-level = "z" # Optimize for size.
lto = true
panic = "abort"
