char = {!(" "|"\""|"="|NEWLINE) ~ ANY}
char_in_quotes = {!("="|"\""|NEWLINE) ~ ANY}
comment = { " "* ~ &"#" ~ (!NEWLINE ~ ANY)* }
options_separator = _{ " "* ~ "=" ~ " "* | " "+ }
empy_line = _{ " "* }
keyword = @{ char+ }
argument = @{ char+ | "\"" ~ char_in_quotes+ ~ "\"" }
host = { " "* ~ !"#" ~ " "* ~ ^"host" ~ options_separator ~ argument }
option = { " "* ~ !"#" ~ " "* ~ keyword ~ options_separator ~ argument }
file = { SOI ~ ((host|option|comment|empy_line)? ~ NEWLINE)* ~ EOI }