char = {!(" "|"\""|"="|NEWLINE) ~ ANY}
char_in_quotes = {!("="|"\""|NEWLINE) ~ ANY}
profile = { " "* ~ "# profile" ~ " "* ~ keyword }
comment = _{ (" "* ~ "#" ~ (!NEWLINE ~ ANY)*) | " "+ }
options_separator = _{ " "* ~ "=" ~ " "* | " "+ }
keyword = @{ char+ }
argument = @{ char+ | "\"" ~ char_in_quotes+ ~ "\"" }
host = { " "* ~ ^"host" ~ options_separator ~ argument ~ " "*}
option = { " "* ~ keyword ~ options_separator ~ argument ~ " "* }
file = { SOI ~ ((profile|host|option|comment)? ~ NEWLINE)* ~ EOI }